Finish ensemble documentation
mitre/menelaus pull request #114
Opened 2022-09-23 17:42 UTC by Anmol-Srivastava

Closes #94 

### Adds
- example script for ensembles

### Changes
- minor formatting issues for existing docstrings in `ensemble.py`

2022-09-23 17:43 UTC, Anmol-Srivastava commented
Waiting on RTD runs now

2022-09-26 19:16 UTC, tms-bananaquit requested changes
Looks good!

One thing that looks a little wonky is `drift_detector `and `ensemble` being unnavigable because of the way they're set in the class hierarchy.
![image](https://user-images.githubusercontent.com/33845624/192359611-645ce26a-9cb3-449f-a1b5-513b7872ab32.png)

The other consequence of having Ensembles/Elections in a single module is that they're mixed in together within the docs, since members are sorted alphabetically right now. I think it'd feel more natural if they were grouped by Ensemble- and Election-related classes; otherwise, we'd have to maintain the order in the source code (everywhere?) and modify some of the sphinx config.

Maybe it would make sense to have a structure like this? The user has to import Elections from `ensemble` right now anyway, so it doesn't seem like it would be a lot of additional pain.
```
/menelaus/
┖ /drift_detector/
   ┖ menelaus.drift_detector
┖ /ensemble/
   ┖ menelaus.ensemble
   ┖ menelaus.election
```

2022-09-26 19:16 UTC, tms-bananaquit commented on examples/ensemble_examples.py
> +# Using an ensemble of streaming detectors can involve additional features. This example uses both data and concept drift detectors (`KdqTreeStreaming`, `STEPD`), custom subsets of data for different
The "different election scheme" here sounds like it's referring to ConfirmedApproval. Should the example or the narrative be modified (in the notebook)?

2022-09-26 19:20 UTC, tms-bananaquit commented on src/menelaus/ensemble.py
>              detectors (dict): Set of detectors in ensemble. Should be keyed by
Could also apply to the same kwarg in `StreamingEnsemble`.

2022-09-30 14:34 UTC, tms-bananaquit approved these changes
Good job! Two typos to fix and then ready to merge.

2022-09-30 14:34 UTC, tms-bananaquit commented on src/menelaus/ensemble/ensemble.py
> +                use this feature. By default, each no column selection
```suggestion
                use this feature. By default, no column selection
```

2022-09-30 14:52 UTC, merged